-- ============================================================
-- Terra Scout V1__init.sql（P0 基线，唯一初始迁移）
-- 目标库：H2 2.2.x（原生模式）
-- 规则：发布后本文件不得修改，变更一律新增 V<n>__*.sql
-- 枚举取值见各表 DDL 定义；error_code 一律 INT（6 位错误码）
-- ============================================================

CREATE TABLE project (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    project_root_path VARCHAR(1024) NOT NULL,
    os_type VARCHAR(32) NOT NULL DEFAULT 'WINDOWS',
    profile_json TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_project_path UNIQUE (project_root_path)
);
CREATE INDEX idx_project_os ON project(os_type);

CREATE TABLE sdk_version (
    id VARCHAR(36) PRIMARY KEY,
    language VARCHAR(32) NOT NULL,
    version VARCHAR(64) NOT NULL,
    os VARCHAR(32) NOT NULL,
    arch VARCHAR(32) NOT NULL,
    download_url VARCHAR(1024) NOT NULL,
    sha256 VARCHAR(128) NOT NULL,
    size_bytes BIGINT,
    lts BOOLEAN NOT NULL DEFAULT FALSE,
    eol BOOLEAN NOT NULL DEFAULT FALSE,
    eol_date DATE,
    cve_count INT NOT NULL DEFAULT 0,
    highest_cve_severity VARCHAR(16) NOT NULL DEFAULT 'NONE',
    license VARCHAR(128),
    distribution VARCHAR(64),
    vendor VARCHAR(128),
    release_time BIGINT,
    created_at BIGINT NOT NULL,
    CONSTRAINT uk_sdk_lang_ver_os_arch UNIQUE (language, version, os, arch)
);
CREATE INDEX idx_sdk_lang ON sdk_version(language);

CREATE TABLE sdk_install_record (
    id VARCHAR(36) PRIMARY KEY,
    language VARCHAR(32) NOT NULL,
    version VARCHAR(64) NOT NULL,
    install_path VARCHAR(1024) NOT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT 'PROJECT',
    project_id VARCHAR(36),
    status VARCHAR(32) NOT NULL,
    checksum VARCHAR(128),
    installed_at BIGINT NOT NULL,
    CONSTRAINT fk_install_project FOREIGN KEY (project_id) REFERENCES project(id)
);
CREATE INDEX idx_install_project ON sdk_install_record(project_id);
CREATE INDEX idx_install_scope ON sdk_install_record(scope);

CREATE TABLE task (
    id VARCHAR(36) PRIMARY KEY,
    parent_id VARCHAR(36),
    task_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload_json TEXT NOT NULL,
    progress DOUBLE NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    max_retry INT NOT NULL DEFAULT 3,
    lock_owner VARCHAR(128),
    heartbeat_at BIGINT,
    error_code INT,
    error_msg TEXT,
    idempotency_key VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT uk_task_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX idx_task_status ON task(status);
CREATE INDEX idx_task_parent ON task(parent_id);

CREATE TABLE task_step (
    id VARCHAR(36) PRIMARY KEY,
    task_id VARCHAR(36) NOT NULL,
    step_index INT NOT NULL,
    step_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_json TEXT,
    output_json TEXT,
    rollback_json TEXT,
    error_code INT,
    error_msg TEXT,
    started_at BIGINT,
    finished_at BIGINT,
    retry_count INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_task_step UNIQUE (task_id, step_index),
    CONSTRAINT fk_step_task FOREIGN KEY (task_id) REFERENCES task(id)
);
CREATE INDEX idx_step_task ON task_step(task_id);
CREATE INDEX idx_step_status ON task_step(status);

CREATE TABLE command_execution (
    id VARCHAR(36) PRIMARY KEY,
    project_id VARCHAR(36),
    command TEXT NOT NULL,
    args_json TEXT NOT NULL,
    work_dir VARCHAR(1024) NOT NULL,
    env_json TEXT,
    exit_code INT,
    stdout_file VARCHAR(1024),
    stderr_file VARCHAR(1024),
    status VARCHAR(32) NOT NULL,
    started_at BIGINT NOT NULL,
    finished_at BIGINT,
    CONSTRAINT fk_cmd_project FOREIGN KEY (project_id) REFERENCES project(id)
);
CREATE INDEX idx_cmd_project ON command_execution(project_id);

CREATE TABLE audit_log (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_id VARCHAR(36) NOT NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(64),
    target_id VARCHAR(36),
    before_json TEXT,
    after_json TEXT,
    result VARCHAR(32) NOT NULL,
    prev_hash VARCHAR(64),
    hash VARCHAR(64) NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL
);
CREATE INDEX idx_audit_biz ON audit_log(biz_id);
CREATE INDEX idx_audit_action ON audit_log(action);
CREATE INDEX idx_audit_created ON audit_log(created_at);
CREATE INDEX idx_audit_seq ON audit_log(seq);
